version: "3.3"

services:
    pypiserver:
        image: pypiserver/pypiserver:v1.2.6
        build:
            context: .
        volumes:
            - ./data/.htpasswd:/data/.htpasswd
            - ./data/welcome.html:/data/welcome.html
            - ./data/packages:/data/packages
        command: -P /data/.htpasswd -a update,download,list --disable-fallback --welcome /data/welcome.html /data/packages
        ports:
            - "8080:8080"
        restart: always

